/**
 * Piper TTS TurboModule spec for the New Architecture.
 * @generated by codegen - do not edit manually.
 */

import type { TurboModule } from 'react-native';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  speak(text: string): Promise<void>;
  isModelAvailable(): Promise<boolean>;
  getDebugInfo(): Promise<string>;
}

export default TurboModuleRegistry.get<Spec>('PiperTts');
