/**
 * Factory for the visualization runtime ref. Single place for default values.
 */

import type { VisualizationEngineRef, VisualizationMode } from './runtimeTypes';

const SENTINEL_FAR = 1e6;

export function createDefaultVisualizationRef(): VisualizationEngineRef {
  return {
    clock: 0,
    activity: 0,
    targetActivity: 0.1,
    voiceEnergy: 0,
    bands: new Float32Array(32),
    pulsePositions: [
      [SENTINEL_FAR, SENTINEL_FAR, SENTINEL_FAR],
      [SENTINEL_FAR, SENTINEL_FAR, SENTINEL_FAR],
      [SENTINEL_FAR, SENTINEL_FAR, SENTINEL_FAR],
    ],
    pulseTimes: [-1e3, -1e3, -1e3],
    pulseColors: [
      [1, 1, 1],
      [1, 1, 1],
      [1, 1, 1],
    ],
    lastPulseIndex: 0,
    lambdaUp: 8,
    lambdaDown: 4,
    paletteId: 0,
    hueShift: 0,
    satBoost: 1,
    lumBoost: 1,
    starCountMultiplier: 1,
    touchActive: false,
    touchNdc: { x: 0, y: 0 },
    touchWorld: null,
    touchView: null,
    touchInfluence: 0,
    pendingTapNdc: null,
    canvasWidth: 1,
    canvasHeight: 1,
    orbitTheta: 0,
    orbitPhi: 0.4,
    autoRotX: 0,
    autoRotY: 0,
    autoRotZ: 0,
    autoRotSpeedX:
      (Math.random() * 0.08 + 0.04) * (Math.random() > 0.5 ? 1 : -1),
    autoRotSpeedY:
      (Math.random() * 0.08 + 0.04) * (Math.random() > 0.5 ? 1 : -1),
    autoRotSpeedZ:
      (Math.random() * 0.04 + 0.02) * (Math.random() > 0.5 ? 1 : -1),
    currentMode: 'idle',
    displayMode: 'idle',
    modeTransitionFrom: 'idle',
    modeTransitionTo: 'idle',
    modeTransitionT: 1,
    postFxEnabled: true,
    postFxVignette: 0.22,
    postFxChromatic: 0.0002,
    postFxGrain: 0.04,
    vizIntensity: 'subtle',
    reduceMotion: false,
    lastEvent: null,
    lastEventTime: 0,
    signalsSnapshot: undefined,
    panelRects: undefined,
    rulesClusterCount: 0,
    cardsClusterCount: 0,
    layerCount: 2,
    deconWeight: 0.2,
    planeOpacity: 0.28,
    driftPx: 2,
    touchFieldActive: false,
    touchFieldNdc: null,
    touchFieldStrength: 0,
    scene: undefined,
    sceneRevision: 0,
    sceneListeners: new Set(),
    zoneArmed: null,
    focusBias: 0,
    touchPresence: 0,
    touchPresenceNdc: { x: 0, y: 0 },
    focusZone: null,
    showTouchZones: false,
    showNameShapingTouchZones: false,
    spineUseHalftonePlanes: false,
    stateCycleOn: false,
    stateCycleTimerId: null,
    stateCycleIdx: 0,
    canonicalCycleOn: false,
    canonicalCycleTimerId: null,
    canonicalCycleIdx: 0,
    debugPulseLoopOn: false,
    debugPulseIntervalMs: 1200,
    debugLastPulseAtMs: 0,
    motionAxisDebug: {
      enabled: false,
      axisLockMode: 'none',
      xGain: 1,
      yGain: 1,
      planeDeformGain: 1,
      planeBendGain: 1,
      planeWarpGain: 1,
      shardDriftGain: 1,
      glyphMotionGain: 1,
    },
    modePinActive: false,
    modePin: null,
  };
}

/** targetActivity by mode (plan §1) */
export const TARGET_ACTIVITY_BY_MODE: Record<VisualizationMode, number> = {
  idle: 0.1,
  listening: 0.6,
  processing: 1.0,
  speaking: 0.7,
  touched: 0.5,
  released: 0.6, // brief then listening
};
